package progPatterns.observerTest;

public class Store {
    int informationForSubscribers = 1;
    String informationForSubscribersString = "Its information generated by event";
    Subscriber<Integer> iGiveYouData;

    public void subscribeOnMe(Subscriber subscriber){
        iGiveYouData = subscriber;
    }

    public void sendInformationToAll(){
        iGiveYouData.whatImDoWhenEventIsHappen(informationForSubscribers);
    }
}
